name: '"Product" deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/product/**'

defaults:
  run:
    working-directory: packages/product

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: product_production

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Build
        run: |
          yarn --frozen-lockfile
          yarn build

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: reggionick/s3-deploy@v3
        with:
          folder: ./packages/product/build
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          bucket-region: eu-central-1
          private: true
          delete-removed: true
          invalidation: /*
