name: Shared package deploy

on:
  push:
    branches:
      - main
    paths:
      - 'packages/shared/**'

defaults:
  run:
    working-directory: packages/shared

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: shared_production

    steps:
      - name: Build
        uses: actions/checkout@v2
        run: |
          yarn
          yarn build

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          bucket-region: eu-central-1
